name = "VueJS"
uuid = "dd23b82c-c6e2-490f-8a36-5dab9c7f2253"
authors = ["Antonio Loureiro <ajose.loureiro@gmail.com>"]
version = "1.0.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Namtso = "14fc9687-df25-4852-9e56-61a08c6e8132"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
DataFrames = "1.2"
HTTP = "0.9"
Namtso = "0.1"
JSON = "0.21"
Highlights = "0.5"
julia = "1.5"
